### ISSUE TITLE
Setting git global settings should probably only be done on AppVeyor

### ISSUE THREAD

**Issue by devlead** [marcosnz/Cake.MSBuildTask#2]
Hi,

Below lines seems a bit "dangerous"
https://github.com/marcosnz/Cake.MSBuildTask/blob/develop/build.cake#L235-L238

Should probably be within the `if (AppVeyor.IsRunningOnAppVeyor)` statement otherwise if anyone forks your repo they will impersonate you :wink:

**Comment by gep13** [comment]
@devlead think this issue can now be closed out, as this has been removed in the forked version.

**Comment by devlead** [comment]
Excellent 👍
