### ISSUE TITLE
cake-contrib user on NuGet

### ISSUE THREAD

**Issue by gep13** [marcosnz/Cake.MSBuildTask#3]
First of all, I wanted to thank you for adding to the Cake community by adding this addin.

I was just wondering if you had seen this blog post:

http://cakebuild.net/blog/2016/08/cake-contribution-organization

We are currently going through a process of increasing the visibility of addins, and also trying to ensure their long term maintainability.

To that end, we are asking addin creators to add the cake-contrib user on NuGet as a co-owner (this can be done through the NuGet website by clicking on `Manage Owners` on the package page).

Would you be interested in doing this for Cake.MSBuildTask?  If you have any questions about this, please let me know.  There was some initial concern that the Cake Team were trying to "take over" packages, and that couldn't be further from the truth, and if you have this concern, or others, I would like to address them.

Thanks!

**Comment by gep13** [comment]
@marcosnz just wanted to touch base to see if you had thought about doing this. Thanks!

**Comment by gep13** [comment]
@marcosnz just wanted to touch base again about this, and wondered if you had a chance to think about it.  Thanks!

**Comment by gep13** [comment]
@marcosnz just wanted to touch base on this again.  What are your thoughts on doing this? Thanks!

**Comment by hurcane** [comment]
I believe the maintainer of this repository died tragically on 22 November 2015. I am interested in being able to use this addin with newer versions of Cake.

I'm not sure what the proper action is in this situation. Should a fork of this repository be made and coordinated with the Cake team? Or maybe the content should be submitted as an integration into the core Cake project? It might fit neatly into the existing MSBuild namespace.

**Comment by gep13** [comment]
@hurcane you may have noticed that i have now forked this repository into the cake-contrib organisation, where we can continue development of the addin.  I am in communication with NuGet regarding getting co-ownership of the package on NuGet.org.  I will report back here once I hear more from them.  Thank you again for bringing this to our attention.

**Comment by gep13** [comment]
With the help of the NuGet team, we have been able to get this resolved.

**Comment by gep13** [comment]
@hurcane We are now in a position where we can push out new package versions of this addin.  You may have noticed that I sent you a GitHub invitation to join the Cake Contributions organisation, which would allow you to help with the maintenance of this project going forward.  Please let me know if you would like to do that.  Thanks!
